name: Deploy to GitHub Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages # Używa sekretów zdefiniowanych w tym środowisku
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.3.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
            VITE_GITHUB_API_URL: ${{ secrets.VITE_GITHUB_API_URL }}
            VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build


          