name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.3.0'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build # lub inna komenda do budowania

      - name: Deploy to GitHub Pages
        env:
            VITE_GITHUB_API_URL: ${{ secrets.VITE_GITHUB_API_URL }}
            VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}
        run: |
          npm install gh-pages
          npx gh-pages -d build -t $VITE_GITHUB_TOKEN


          
